changesetBaseRefs:
  - prod
  - origin/prod

enableMessageNames: false

packageExtensions:
  "@google-cloud/opentelemetry-cloud-trace-exporter@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@mui/system@*":
    peerDependencies:
      react-dom: "*"
      react-is: "*"
      styled-components: "*"
  "@mui/material@*":
    peerDependencies:
      styled-components: "*"
  "@mui/lab@*":
    peerDependencies:
      styled-components: "*"
  html-webpack-live-reload-plugin@*:
    peerDependencies:
      webpack: ^5
  next@*:
    peerDependencies:
      react-dom: "*"
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.4.cjs
