export const CUBE_PREVIEW_FIELDS: "_id shortID image_uri image_name image_artist name owner owner_name type card_count overrideCategory categoryPrefixes categoryOverride date_updated";
export function redirectToLandingOrDash(req: any, res: any): any;
export const getChildComments: (req: any, res: any, next: any) => Promise<any>;
export function showDowntimePage(req: any, res: any): Promise<void>;
export const exploreCubes: (req: any, res: any, next: any) => Promise<any>;
export const showRandomCube: (req: any, res: any, next: any) => Promise<any>;
export const viewDashboard: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const getDashboardDecks: (req: any, res: any, next: any) => Promise<any>;
export const viewLanding: (req: any, res: any, next: any) => Promise<any>;
export function getVersion(req: any, res: any): Promise<void>;
export function viewSearchPage(req: any, res: any): Promise<void>;
export function searchResultsPage(req: any, res: any): Promise<void>;
export function showLeavePage(req: any, res: any): Promise<void>;
export function showErrorPage(req: any, res: any): Promise<any>;
export function browsePackages(req: any, res: any): Promise<void>;
export function loginUser(req: any, res: any, next: any): void;
export function logoutUser(req: any, res: any): void;
export function addMinutes(date: any, minutes: any): Date;
export const submitLostPassword: ((req: any, _res: any, next: any) => void)[];
export const resetPassword: ((req: any, _res: any, next: any) => void)[];
export const viewLostPasswordPage: (req: any, res: any, next: any) => Promise<any>;
export const viewLoginPage: (req: any, res: any, next: any) => Promise<any>;
//# sourceMappingURL=misc.d.ts.map