import { amber, blue, cyan, green, mauve, purple, tomato } from '@radix-ui/colors/src';
import { createTheme } from '@vanilla-extract/css';

import baseThemeContract from '@cubeartisan/cubeartisan/styles/themes/base.css';

export const lightTheme = createTheme(baseThemeContract, {
  color: {
    primary: {
      1: purple.purple1,
      2: purple.purple2,
      3: purple.purple3,
      4: purple.purple4,
      5: purple.purple5,
      6: purple.purple6,
      7: purple.purple7,
      8: purple.purple8,
      9: purple.purple9,
      10: purple.purple10,
      11: purple.purple11,
      12: purple.purple12,
    },
    secondary: {
      1: cyan.cyan1,
      2: cyan.cyan2,
      3: cyan.cyan3,
      4: cyan.cyan4,
      5: cyan.cyan5,
      6: cyan.cyan6,
      7: cyan.cyan7,
      8: cyan.cyan8,
      9: cyan.cyan9,
      10: cyan.cyan10,
      11: cyan.cyan11,
      12: cyan.cyan12,
    },
    neutral: {
      1: mauve.mauve1,
      2: mauve.mauve2,
      3: mauve.mauve3,
      4: mauve.mauve4,
      5: mauve.mauve5,
      6: mauve.mauve6,
      7: mauve.mauve7,
      8: mauve.mauve8,
      9: mauve.mauve9,
      10: mauve.mauve10,
      11: mauve.mauve11,
      12: mauve.mauve12,
    },
    success: {
      1: green.green1,
      2: green.green2,
      3: green.green3,
      4: green.green4,
      5: green.green5,
      6: green.green6,
      7: green.green7,
      8: green.green8,
      9: green.green9,
      10: green.green10,
      11: green.green11,
      12: green.green12,
    },
    info: {
      1: blue.blue1,
      2: blue.blue2,
      3: blue.blue3,
      4: blue.blue4,
      5: blue.blue5,
      6: blue.blue6,
      7: blue.blue7,
      8: blue.blue8,
      9: blue.blue9,
      10: blue.blue10,
      11: blue.blue11,
      12: blue.blue12,
    },
    warning: {
      1: amber.amber1,
      2: amber.amber2,
      3: amber.amber3,
      4: amber.amber4,
      5: amber.amber5,
      6: amber.amber6,
      7: amber.amber7,
      8: amber.amber8,
      9: amber.amber9,
      10: amber.amber10,
      11: amber.amber11,
      12: amber.amber12,
    },
    danger: {
      1: tomato.tomato1,
      2: tomato.tomato2,
      3: tomato.tomato3,
      4: tomato.tomato4,
      5: tomato.tomato5,
      6: tomato.tomato6,
      7: tomato.tomato7,
      8: tomato.tomato8,
      9: tomato.tomato9,
      10: tomato.tomato10,
      11: tomato.tomato11,
      12: tomato.tomato12,
    },
  },
});
