import { blackA, mauve, mauveDark, whiteA } from '@radix-ui/colors/src';

export const colors = {
  white: '#fff',
  black: '#121212',
  grayLight: {
    1: mauve.mauve1,
    2: mauve.mauve2,
    3: mauve.mauve3,
    4: mauve.mauve4,
    5: mauve.mauve5,
    6: mauve.mauve6,
    7: mauve.mauve7,
    8: mauve.mauve8,
    9: mauve.mauve9,
    10: mauve.mauve10,
    11: mauve.mauve11,
    12: mauve.mauve12,
  },
  grayDark: {
    1: mauveDark.mauve1,
    2: mauveDark.mauve2,
    3: mauveDark.mauve3,
    4: mauveDark.mauve4,
    5: mauveDark.mauve5,
    6: mauveDark.mauve6,
    7: mauveDark.mauve7,
    8: mauveDark.mauve8,
    9: mauveDark.mauve9,
    10: mauveDark.mauve10,
    11: mauveDark.mauve11,
    12: mauveDark.mauve12,
  },
  shadowLight: {
    1: whiteA.whiteA1,
    2: whiteA.whiteA2,
    3: whiteA.whiteA3,
    4: whiteA.whiteA4,
    5: whiteA.whiteA5,
    6: whiteA.whiteA6,
    7: whiteA.whiteA7,
    8: whiteA.whiteA8,
    9: whiteA.whiteA9,
    10: whiteA.whiteA10,
    11: whiteA.whiteA11,
    12: whiteA.whiteA12,
  },
  shadowDark: {
    1: blackA.blackA1,
    2: blackA.blackA2,
    3: blackA.blackA3,
    4: blackA.blackA4,
    5: blackA.blackA5,
    6: blackA.blackA6,
    7: blackA.blackA7,
    8: blackA.blackA8,
    9: blackA.blackA9,
    10: blackA.blackA10,
    11: blackA.blackA11,
    12: blackA.blackA12,
  },
} as const;
