export const createCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any) => Promise<any>))[];
export const cloneCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const addFormat: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any) => Promise<any>))[];
export const featureCube: ((req: any, res: any, next: any) => any)[];
export const unfeatureCube: ((req: any, res: any, next: any) => any)[];
export function viewOverview(req: any, res: any): Promise<any>;
export const getRss: (req: any, res: any, next: any) => Promise<any>;
export const viewCubeComparison: (req: any, res: any, next: any) => Promise<any>;
export function viewCubeList(req: any, res: any): Promise<any>;
export function viewPlaytest(req: any, res: any): Promise<any>;
export function viewAnalytics(req: any, res: any): Promise<any>;
export function redirectToSamplePackWithSeed(req: any, res: any): any;
export function viewSamplePack(req: any, res: any): Promise<any>;
export const viewSamplePackImage: ((_req: any, res: any, next: any) => void)[];
export const startGridDraft: (import("express-validator").ValidationChain | ((req: any, res: any) => Promise<any>))[];
export const startDraft: (import("express-validator").ValidationChain | ((req: any, res: any) => Promise<any>))[];
export const editCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any) => Promise<any>))[];
export const resizeCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any) => Promise<any>))[];
export const deleteCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const deleteFormat: (import("express-validator").ValidationChain | ((req: any, res: any, next: any) => any)[] | ((req: any, res: any) => Promise<any>))[];
export const setDefaultFormat: (import("express-validator").ValidationChain | ((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const editCubeOverview: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => void))[];
export const updateCubeSettings: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => void))[];
export const getCardNamesForCube: (req: any, res: any, next: any) => Promise<any>;
export const getCardTagsForCube: (req: any, res: any, next: any) => Promise<any>;
export const updateTagColors: (req: any, res: any, next: any) => Promise<any>;
export const getTagColors: (req: any, res: any, next: any) => Promise<any>;
export const getCardInCubeByName: (req: any, res: any, next: any) => Promise<any>;
export const updateCubeBasics: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const getDefaultPrinting: (req: any, res: any, next: any) => Promise<any>;
export const updateCardInCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const updateCardsInCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export function getMaybeboard(req: any, res: any): Promise<any>;
export const addCardsToCube: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const updateMaybeboard: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const updateMaybeboardCard: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const updateCubeSorts: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export const generateP1P1: (req: any, res: any, next: any) => Promise<any>;
export const getDateCubeUpdated: (req: any, res: any, next: any) => Promise<any>;
export const getRecommendations: (req: any, res: any, next: any) => Promise<any>;
export function getCardImageById(req: any, res: any): Promise<any>;
export function viewCubeDecks(req: any, res: any): Promise<any>;
export const uploadDeckList: (((req: any, res: any, next: any) => any)[] | ((req: any, res: any, next: any) => Promise<any>))[];
export function redirectToFirstPageOfCubeBlog(req: any, res: any): any;
export function addSeedToP1P1(req: any, res: any): any;
export function redirectToFirstPageOfCubeDecks(req: any, res: any): any;
//# sourceMappingURL=index.d.ts.map