import {
  tomatoDark as danger,
  blueDark as info,
  mauveDark as neutral,
  purpleDark as primary,
  whiteA as shadow,
  greenDark as success,
  amberDark as warning,
} from '@radix-ui/colors/src';

import type { ColorPaletteType } from '@cubeartisan/cubeartisan/styles/themes/colorPaletteType';

export const colorPalette: ColorPaletteType = {
  neutral1: neutral.mauve1,
  neutral2: neutral.mauve2,
  neutral3: neutral.mauve3,
  neutral4: neutral.mauve4,
  neutral5: neutral.mauve5,
  neutral6: neutral.mauve6,
  neutral7: neutral.mauve7,
  neutral8: neutral.mauve8,
  neutral9: neutral.mauve9,
  neutral10: neutral.mauve10,
  neutral11: neutral.mauve11,
  neutral12: neutral.mauve12,
  primary1: primary.purple1,
  primary2: primary.purple2,
  primary3: primary.purple3,
  primary4: primary.purple4,
  primary5: primary.purple5,
  primary6: primary.purple6,
  primary7: primary.purple7,
  primary8: primary.purple8,
  primary9: primary.purple9,
  primary10: primary.purple10,
  primary11: primary.purple11,
  primary12: primary.purple12,
  success1: success.green1,
  success2: success.green2,
  success3: success.green3,
  success4: success.green4,
  success5: success.green5,
  success6: success.green6,
  success7: success.green7,
  success8: success.green8,
  success9: success.green9,
  success10: success.green10,
  success11: success.green11,
  success12: success.green12,
  info1: info.blue1,
  info2: info.blue2,
  info3: info.blue3,
  info4: info.blue4,
  info5: info.blue5,
  info6: info.blue6,
  info7: info.blue7,
  info8: info.blue8,
  info9: info.blue9,
  info10: info.blue10,
  info11: info.blue11,
  info12: info.blue12,
  warning1: warning.amber1,
  warning2: warning.amber2,
  warning3: warning.amber3,
  warning4: warning.amber4,
  warning5: warning.amber5,
  warning6: warning.amber6,
  warning7: warning.amber7,
  warning8: warning.amber8,
  warning9: warning.amber9,
  warning10: warning.amber10,
  warning11: warning.amber11,
  warning12: warning.amber12,
  danger1: danger.tomato1,
  danger2: danger.tomato2,
  danger3: danger.tomato3,
  danger4: danger.tomato4,
  danger5: danger.tomato5,
  danger6: danger.tomato6,
  danger7: danger.tomato7,
  danger8: danger.tomato8,
  danger9: danger.tomato9,
  danger10: danger.tomato10,
  danger11: danger.tomato11,
  danger12: danger.tomato12,
  shadow1: shadow.whiteA1,
  shadow2: shadow.whiteA2,
  shadow3: shadow.whiteA3,
  shadow4: shadow.whiteA4,
  shadow5: shadow.whiteA5,
  shadow6: shadow.whiteA6,
  shadow7: shadow.whiteA7,
  shadow8: shadow.whiteA8,
  shadow9: shadow.whiteA9,
  shadow10: shadow.whiteA10,
  shadow11: shadow.whiteA11,
  shadow12: shadow.whiteA12,
} as const;
