import {
  tomatoDark as danger,
  blueDark as info,
  mauveDark as neutral,
  purpleDark as primary,
  whiteA as shadow,
  greenDark as success,
  amberDark as warning,
} from '@radix-ui/colors/src';

import type { ColorPaletteType } from '@cubeartisan/cubeartisan/styles/themes/colorPaletteType';

export const colorPalette: ColorPaletteType = {
  neutral: {
    1: neutral.mauve1,
    2: neutral.mauve2,
    3: neutral.mauve3,
    4: neutral.mauve4,
    5: neutral.mauve5,
    6: neutral.mauve6,
    7: neutral.mauve7,
    8: neutral.mauve8,
    9: neutral.mauve9,
    10: neutral.mauve10,
    11: neutral.mauve11,
    12: neutral.mauve12,
  },
  primary: {
    1: primary.purple1,
    2: primary.purple2,
    3: primary.purple3,
    4: primary.purple4,
    5: primary.purple5,
    6: primary.purple6,
    7: primary.purple7,
    8: primary.purple8,
    9: primary.purple9,
    10: primary.purple10,
    11: primary.purple11,
    12: primary.purple12,
  },
  success: {
    1: success.green1,
    2: success.green2,
    3: success.green3,
    4: success.green4,
    5: success.green5,
    6: success.green6,
    7: success.green7,
    8: success.green8,
    9: success.green9,
    10: success.green10,
    11: success.green11,
    12: success.green12,
  },
  info: {
    1: info.blue1,
    2: info.blue2,
    3: info.blue3,
    4: info.blue4,
    5: info.blue5,
    6: info.blue6,
    7: info.blue7,
    8: info.blue8,
    9: info.blue9,
    10: info.blue10,
    11: info.blue11,
    12: info.blue12,
  },
  warning: {
    1: warning.amber1,
    2: warning.amber2,
    3: warning.amber3,
    4: warning.amber4,
    5: warning.amber5,
    6: warning.amber6,
    7: warning.amber7,
    8: warning.amber8,
    9: warning.amber9,
    10: warning.amber10,
    11: warning.amber11,
    12: warning.amber12,
  },
  danger: {
    1: danger.tomato1,
    2: danger.tomato2,
    3: danger.tomato3,
    4: danger.tomato4,
    5: danger.tomato5,
    6: danger.tomato6,
    7: danger.tomato7,
    8: danger.tomato8,
    9: danger.tomato9,
    10: danger.tomato10,
    11: danger.tomato11,
    12: danger.tomato12,
  },
  shadow: {
    1: shadow.whiteA1,
    2: shadow.whiteA2,
    3: shadow.whiteA3,
    4: shadow.whiteA4,
    5: shadow.whiteA5,
    6: shadow.whiteA6,
    7: shadow.whiteA7,
    8: shadow.whiteA8,
    9: shadow.whiteA9,
    10: shadow.whiteA10,
    11: shadow.whiteA11,
    12: shadow.whiteA12,
  },
} as const;
