name: Continuous Integration Checks
on: [push, pull_request]
jobs:
  "Continuous_Integration_Checks":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.10'
        cache: 'yarn'
    - name: Setup
      run: yarn install --frozen-lockfile --production=false || yarn install --frozen-lockfile --production=false || yarn install --frozen-lockfile --production=false
    - name: Run the CI script in yarn to check code style and unit tests.
      run: yarn ci
